# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py

# (Opcional) Si tu doc usa extensiones o temas, instala requerimientos
python:
  install:
    - requirements: docs/requirements.txt
